language: node_js
node_js:
- '8'
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: gElbY2HYo1WtEfYhT+5Nu3A4vcVEUCbVt0oeprlsvgxtW1gTSeATSzc9zQKRGEBKp1wwd7VKy14e9lFd8XEKZQ6Wq9/Z5hlGVMnOSrM2Aon0W3pcb9uR5M2JClK+R7hAWpqIB3TG57u7v7/I538juyytTv94RwG/U0/7EdREnBBhPaVQwoqZ3Hz4fmFgGe5ziRhKXztttTsQSTensgG7jsz1xBD+qRATqWFCXMRZwoXKyPUmIs/tUT09pM406lioqiRjvCO7Mtaeupea8zcyn7DVWFYvyLLIcWgGnvJ2DLWwlp+ASaxqGZIuCMZakps+oyrv3h3Wis0qjnCJM8XLk29Almdrg8yBVjIu6ImRbakqhFUPcfMmT5MfzrmKeFxYwIOrkLyfUQmUDOS5h/UMmz1FJbzuqtWfonf3juHjQ4ksWwCgUjwlmSFah8IkuE2sI3So7kDRWpOwnUbcee/OBYd3K3Uc6xNfFqJVpgrV/MvOtYrdOC96bxIX7ImsUgsQTeXeuiEeyA6VPr6j/+ZfYDMpVoVFOgJLcDYrIrjPWWJHEWinPA5Lihk8YkDqOCP46DNXtvLSu6PCtORKgml9z1Q6ZsjEOnVlRgMiSTdOI5dz4O01/x8wA03JuC4zREz3UFTqtxwgK65rJqahz/YPO0iWirbDpSTtTsVe4xGX4Nc=
  app: devmeetings-eventbrite-dashboard
  on:
    repo: lukaszewczak/devmeetings-eventbrite-dashboard
