language: node_js
node_js:
- '8'
script:
- npm test
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: nsLqiL46gV0pvalUPCfLpTXPVpTYB7ZJL8QnnrhmjQOj7anpRGEprvqBdevxsXef42EjWO0lYTNFvclDc6sI+oaV+RgW/lID6xf5CO/QJCIJpBcyMsrOlYSnt17wqgtNbyAI9jwyu4Y2aC/crYBirtzjmKeGWdbxMDdYL/OPIh7FHBhvRPPAH9ze2owTNNzqUF7o8QeudnzJUgETlK5nEWFbHwVuxSWaKl+5qvnZmLXDLq+km0heRGFMPk6yu/mCz5kKQDZbs13IC4ZtWvW5BWH+qkZlXuNJaCjI9v1y4q/JrLiMq5UGxY9uoH2JIiZw3XQi0tqPStc8YxLdm4ax2KoPTSJ6Jkn1KNzv6Vv33gE4reh5Wz4k4miNDFxz2WRTOj8r4ixftbIrPuvI1l5qAHAfLFFpA3nDateyFNAtxlP7VbBxQ9wT8YqumLu4ErmhabsWF/mU1m3Mo4aseAt2397Q5WCcTKStj7cFSv28x8IPrhqoS5S+TT2DbAxeGpIR0cDRGYGf9UhIEbC8lpWqSfROCB77yCQobcGaaBbCZjAxz8eVr499p+rQOSuOoesE+3IN7mg6/oxS1LCGta2P/6WZnqgyLMOEyzQWcBHMA3vQlP+XnYFR5TmA8vmgRbOo8wB93BExwgESLZXmLrSoITCn1gAZz0tcv37XmC4vWYc=
  app: devmeetings-dashboard
  on:
    repo: lukaszewczak/devmeetings-eventbrite-dashboard
